### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by ac12644** [PacktPublishing/Security-Tokens-and-Stablecoins-Quick-Start-Guide#12]
57 passing and 29 tests are failing
<img width="831" alt="Screenshot 2022-08-01 at 22 53 59" src="https://user-images.githubusercontent.com/43683452/182245054-8fb7d0e4-7f3a-4719-8fe5-37532917964a.png">

**Comment by saurabhk710** [comment]
Hi @ac12644 
This could be caused by the solidity, truffle version, or other lib changes. The smart contract version we used in this book is 0.4.24, which is quite old. In this case, the user may need to debug it. 
One suggestion is to add a console log to see the different values between actual and expected data.
  it('should have a decimals value on the token contract', async () => {
    const _decimals = await token.decimals()
    console.log("_decimals", _decimals );
    console.log("decimals", decimals);
    assert(_decimals.eq(decimals))
  })
